[BonDriver_LinuxMirakurun]

; --------------------------------------------------
; ログ設定
; --------------------------------------------------
; BonDriver のログレベルを設定します
; 4 : info    (通常の動作ログのみ)
; 6 : verbose (トラブルシューティング用)
LogLevel=4

; http通信に関する詳細なデバッグログを出力します (true/false) (初期値: false)
; HttpVerboseLog=false

; --------------------------------------------------
; 接続先設定
; --------------------------------------------------
; Mirakurun サーバーのアドレスとポートを指定します
; HTTP               ： http://<ip address>:<port>
; UNIXドメインソケット : unix://<full path>
ServerAddress=http://127.0.0.1:40772
; ServerAddress=unix:///opt/mirakurun/run/mirakurun.sock

; --------------------------------------------------
; タイムアウト設定 (単位: ms)
; --------------------------------------------------
; チャンネル一覧を取得する際の接続待ち時間の上限を設定します（初期値: 500)
; ChannelListTimeout=500

; 通常の通信時における接続待ち時間の上限を設定します (初期値: 1000)
; SessionTimeout=1000

; TS転送が終了・切断されたと判定するまでの待ち時間上限 (初期値: 2000)
; ResponseTimeout=2000

; --------------------------------------------------
; バッファ・転送サイズ設定
; --------------------------------------------------
; TS転送用リングバッファのサイズを指定します (単位: byte) (初期値: 4194304)
; StreamBufferSize=4194304

; GetTsStream呼び出し時に、一度に返却するTSデータのサイズを「パケット数」で指定します (初期値: 2048)
; 指定したパケット数 × 188 バイト単位でデータが返されます
; TsPacketsPerChunk=2048

; --------------------------------------------------
; チャンネル制限設定
; --------------------------------------------------
; 手動チャンネルリスト(UseManualChannelList=1)使用時の、最大読み込みチャンネル数 (初期値: 300)
; Ch0 からカウントし、設定値以降のチャンネルは無視されます。また、欠番以降も無意します
; MaximumNumberOfChannels=300

[Space]
; BonDriver のチャンネル空間 (TuningSpace) を設定
; Space=UHF
Space=UHF,BS,CS110
; Space=UHF,BS,CS110,CATV

[Space.UHF]
Name=地デジ(UHF)
Type=GR
UseManualChannelList=0
B25Decode=0
Priority=10

; UseManualChannelList
; 0 ： Mirakurun から取得したチャンネルリストを使用します
; 1 ： 以下に定義した手動チャンネルリストを使用します
; Chx=BonDriverの初期チャンネル名,Mirakurunのチャンネル名

; [Space.UHF.Channel]
; Ch0=13ch,13
; Ch1=14ch,14
; Ch2=15ch,15
; Ch3=16ch,16
; Ch4=17ch,17
; Ch5=18ch,18
; Ch6=19ch,19
; Ch7=20ch,20
; Ch8=21ch,21
; Ch9=22ch,22
; Ch10=23ch,23
; Ch11=24ch,24
; Ch12=25ch,25
; Ch13=26ch,26
; Ch14=27ch,27
; Ch15=28ch,28
; Ch16=29ch,29
; Ch17=30ch,30
; Ch18=31ch,31
; Ch19=32ch,32
; Ch20=33ch,33
; Ch21=34ch,34
; Ch22=35ch,35
; Ch23=36ch,36
; Ch24=37ch,37
; Ch25=38ch,38
; Ch26=39ch,39
; Ch27=40ch,40
; Ch28=41ch,41
; Ch29=42ch,42
; Ch30=43ch,43
; Ch31=44ch,44
; Ch32=45ch,45
; Ch33=46ch,46
; Ch34=47ch,47
; Ch35=48ch,48
; Ch36=49ch,49
; Ch37=50ch,50
; Ch38=51ch,51
; Ch39=52ch,52
; Ch40=53ch,53
; Ch41=54ch,54
; Ch42=55ch,55
; Ch43=56ch,56
; Ch44=57ch,57
; Ch45=58ch,58
; Ch46=59ch,59
; Ch47=60ch,60
; Ch48=61ch,61
; Ch49=62ch,62

[Space.BS]
Name=BS
Type=BS
UseManualChannelList=0
B25Decode=0
Priority=10

; [Space.BS.Channel]
; Ch0=BS01/TS0,BS01_0
; Ch1=BS01/TS1,BS01_1
; Ch2=BS01/TS2,BS01_2
; Ch3=BS03/TS0,BS03_0
; Ch4=BS03/TS1,BS03_1
; Ch5=BS03/TS2,BS03_2
; Ch6=BS05/TS0,BS05_0
; Ch7=BS05/TS1,BS03_1
; Ch8=BS09/TS0,BS09_0
; Ch9=BS09/TS2,BS09_2
; Ch10=BS13/TS0,BS13_0
; Ch11=BS13/TS1,BS13_1
; Ch12=BS13/TS2,BS13_2
; Ch13=BS15/TS1,BS15_1
; Ch14=BS15/TS2,BS15_2
; Ch15=BS15/TS3,BS15_3
; Ch16=BS19/TS0,BS19_0
; Ch17=BS19/TS1,BS19_1
; Ch18=BS19/TS2,BS15_2
; Ch19=BS19/TS3,BS19_3
; Ch20=BS21/TS0,BS21_0
; Ch21=BS21/TS1,BS21_1
; Ch22=BS21/TS2,BS21_2
; Ch23=BS23/TS0,BS23_0
; Ch24=BS23/TS1,BS23_1
; Ch25=BS23/TS3,BS23_3

[Space.CS110]
Name=CS110
Type=CS
UseManualChannelList=0
B25Decode=0
Priority=10

; [Space.CS110.Channel]
; Ch0=ND02/TS0,CS2
; Ch1=ND04/TS0,CS4
; Ch2=ND06/TS0,CS6
; Ch3=ND08/TS0,CS8
; Ch4=ND10/TS0,CS10
; Ch5=ND12/TS0,CS12
; Ch6=ND14/TS0,CS14
; Ch7=ND16/TS0,CS16
; Ch8=ND18/TS0,CS18
; Ch9=ND20/TS0,CS20
; Ch10=ND22/TS0,CS22
; Ch11=ND24/TS0,CS24

[Space.CATV]
Name=CATV
Type=SKY
UseManualChannelList=0
B25Decode=0
Priority=10

; [Space.CATV.Channel]
; Ch0=C13ch,C13
; Ch1=C14ch,C14
; Ch2=C15ch,C15
; Ch3=C16ch,C16
; Ch4=C17ch,C17
; Ch5=C18ch,C18
; Ch6=C19ch,C19
; Ch7=C20ch,C20
; Ch8=C21ch,C21
; Ch9=C22ch,C22
; Ch10=C23ch,C23
; Ch11=C24ch,C24
; Ch12=C25ch,C25
; Ch13=C26ch,C26
; Ch14=C27ch,C27
; Ch15=C28ch,C28
; Ch16=C29ch,C29
; Ch17=C30ch,C30
; Ch18=C31ch,C31
; Ch19=C32ch,C32
; Ch20=C33ch,C33
; Ch21=C34ch,C34
; Ch22=C35ch,C35
; Ch23=C36ch,C36
; Ch24=C37ch,C37
; Ch25=C38ch,C38
; Ch26=C39ch,C39
; Ch27=C40ch,C40
; Ch28=C41ch,C41
; Ch29=C42ch,C42
; Ch30=C43ch,C43
; Ch31=C44ch,C44
; Ch32=C45ch,C45
; Ch33=C46ch,C46
; Ch34=C47ch,C47
; Ch35=C48ch,C48
; Ch36=C49ch,C49
; Ch37=C50ch,C50
; Ch38=C51ch,C51
; Ch39=C52ch,C52
; Ch40=C53ch,C53
; Ch41=C54ch,C54
; Ch42=C55ch,C55
; Ch43=C56ch,C56
; Ch44=C57ch,C57
; Ch45=C58ch,C58
; Ch46=C59ch,C59
; Ch47=C60ch,C60
; Ch48=C61ch,C61
; Ch49=C62ch,C62
